export const STOP_WORDS = new Set([
  // Spanish
  'de', 'la', 'que', 'el', 'en', 'y', 'a', 'los', 'del', 'se', 'las', 'por',
  'un', 'para', 'con', 'no', 'una', 'su', 'al', 'lo', 'como', 'más', 'mas',
  'pero', 'sus', 'le', 'ya', 'o', 'este', 'sí', 'si', 'porque', 'esta',
  'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay',
  'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les',
  'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'e', 'esto', 'mí',
  'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él',
  'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'muchos', 'cual',
  'poco', 'ella', 'estar', 'estas', 'algunas', 'algo', 'nosotros', 'mi',
  'mis', 'tú', 'te', 'ti', 'tu', 'tus', 'ellas', 'nosotras', 'vosotros',
  'vosotras', 'os', 'mío', 'mía', 'míos', 'mías', 'tuyo', 'tuya', 'tuyos',
  'tuyas', 'suyo', 'suya', 'suyos', 'suyas', 'nuestro', 'nuestra', 'nuestros',
  'nuestras', 'vuestro', 'vuestra', 'vuestros', 'vuestras', 'esos', 'esas',
  'estoy', 'estás', 'está', 'estamos', 'estáis', 'están', 'esté', 'estés',
  'estemos', 'estéis', 'estén', 'estaré', 'estarás', 'estará', 'estaremos',
  'estaréis', 'estarán', 'he', 'has', 'ha', 'hemos', 'habéis', 'han', 'ser',
  'es', 'soy', 'eres', 'somos', 'sois', 'son', 'era', 'fue', 'sido', 'sea',
  'tengo', 'tienes', 'tiene', 'tenemos', 'tienen', 'tener', 'haber', 'hacer',
  'cada', 'yo', 'nos', 'les', 'ver', 'ir', 'da', 'dan', 'dio', 'van', 'voy',
  'vas', 'va', 'dijo', 'hay', 'bien', 'así', 'aquí', 'ahora', 'luego',
  'después', 'entonces', 'pues', 'bueno', 'solo', 'sólo', 'puede', 'tal',
  // Common WhatsApp words to filter
  'jajaja', 'jajajaja', 'jaja', 'jajaj', 'xd', 'xdd', 'jeje', 'jejeje',
  'ok', 'vale', 'imagen', 'omitida', 'omitido', 'media', 'omitted',
  'audio', 'video', 'sticker', 'gif', 'documento', 'https', 'http', 'www',
  // English
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'it',
  'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but',
  'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will',
  'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out',
  'if', 'about', 'who', 'get', 'which', 'go', 'me', 'when', 'make', 'can',
  'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people', 'into',
  'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than',
  'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well',
  'way', 'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day',
  'most', 'us', 'is', 'am', 'are', 'was', 'were', 'been', 'being', 'has',
  'had', 'did', 'does', 'doing', 'will', 'shall', 'should', 'may', 'might',
  'must', 'need', 'dare', 'ought', 'used', 'going', 'gone', 'got', 'getting',
  'yes', 'yeah', 'yep', 'nope', 'lol', 'haha', 'hahaha', 'hmm', 'oh', 'ah',
]);
